# Site settings
title: bunting.io
email: jared@bunting.io
description: > # this means to ignore newlines until "baseurl:"
  I write software and I tinker around with several other crafts. I do my best
  to write about things that I learn or that capture my interest. You may find
  those writings here.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bunting.io" # the base hostname & protocol for your site
twitter_username: jwbunt
github_username:  jbunting

# Build settings
markdown: kramdown
